package EduMaps::Schema;
use Mojo::Base 'DBIx::Class::Schema', -strict, -signatures;
use Role::Tiny::With;
use utf8;

with "EduMaps::Roles::DB::$_" for qw/InjectRelation InjectSimilarityRelation/;

sub go {
  my $class = shift;

  my $conf_file = $ENV{EDUMAPS_CONF} || './edu_maps.conf';
  die "$conf_file not found configuration file" unless -f $conf_file;
  my $params = do $conf_file;
  my @db_params = (
    $params->{db_params}->@*,
    $params->{db_opts},
  );
  return $class->connect(@db_params);
}

{ 
  # silence the warning generated by load_namespaces() because our 
  # base class is not a ResultSet (in sense of a table proxie). And more
  # a common sense ground for all ResultSets
  local $SIG{__WARN__} = sub {
    my $msg = shift;
    warn $msg unless $msg =~ /load_namespaces found ResultSet class .* with no corresponding Result class/i;
  };
  __PACKAGE__->load_namespaces(
    result_namespace => [qw(Result Result::View)],
    resultset_namespace => [qw(ResultSet)],
  );
}

1;
